apiVersion: v1
kind: ConfigMap
metadata:
  name: request-service-config
  namespace: carpooling
data:
  HTTP_ADDR: ":8080"
  AWS_REGION: "us-east-1"
  DB_SECRET_ARN: ${DB_SECRET_ARN}
  DB_HOST: ${DB_HOST}
  DB_PORT: "5432"
  DB_NAME: ${DB_NAME}
  DB_SSL_MODE: "require"
  SNS_MATCH_CREATED_ARN: "arn:aws:sns:us-east-1:670636167354:match_created_event"
  SNS_MATCH_CANCELLED_ARN: "arn:aws:sns:us-east-1:670636167354:match_cancelled_event"
  LOG_LEVEL: "info"

